name: tydchronos_wallet
description: TydChronos Advanced Crypto Wallet and E-wallet
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.3
  logger: ^2.0.0
  http: ^1.1.0
  web_socket_channel: 2.4.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.11
  crypto: ^3.0.3
  encrypt: ^5.0.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  provider: ^6.1.1
  ed25519_hd_key: ^2.0.1
  hex: ^0.2.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo.png
    - assets/icon/icon.png